services:

  mongoDB:
    restart: always
    image: docker.io/library/mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data_vol:/data/db

  owaspZap:
    restart: always
    image: ghcr.io/zaproxy/zaproxy:stable
    ports:
      - 127.0.0.1:8888:8888
    # -addoninstall
    command: zap.sh -addonupdate -daemon -host 0.0.0.0 -port 8888 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true -Xmx4096m
    environment:
      ZAP_PORT: 8888

  kaliLinux:
    restart: "no"
    image: docker.io/trolleye/kali-linux:latest
    profiles:
      - disable

  netRecon:
    restart: "no"
    image: docker.io/trolleye/netrecon:latest
    profiles:
      - disable

  snyk-cli:
    restart: "no"
    image: docker.io/trolleye/snyk-cli:latest
    profiles:
      - disable

volumes:
  mongodb_data_vol:

