services:

  mongoDB:
    restart: always
    image: docker.io/library/mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data_vol:/data/db

  owaspZap:
    restart: always
    image: ghcr.io/zaproxy/zaproxy:stable
    ports:
      - 127.0.0.1:8888:8888
    # -addoninstall
    command: zap.sh -addonupdate -daemon -host 0.0.0.0 -port 8888 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true -Xmx4096m
    environment:
      ZAP_PORT: 8888

  metasploit:
    image: metasploitframework/metasploit-framework:latest
    #environment:
    #  DATABASE_URL: postgres://postgres@db:5432/msf?pool=200&timeout=5
    #links:
    #  - db
    ports:
      - 127.0.0.1:55553:55553
    volumes:
      - metasploit_data_vol:/data/metasploit

  kaliLinux:
    restart: "no"
    image: docker.io/trolleye/kali-linux:latest
    profiles:
      - disable

  netRecon:
    restart: "no"
    image: docker.io/trolleye/netrecon:latest
    profiles:
      - disable

  snyk-cli:
    restart: "no"
    image: docker.io/trolleye/snyk-cli:latest
    profiles:
      - disable

  nmap:
    restart: "no"
    image: docker.io/trolleye/nmap:7.95
    profiles:
      - disable

volumes:
  mongodb_data_vol:
  metasploit_data_vol:
